### ISSUE TITLE
使用pip install qcos安装时，会报错

### ISSUE THREAD

**Issue by mtooooo** [codeif/qcos#1]
File "setup.py", line 5, in <module>
      readme = f.read()
  UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 21: illegal multibyte sequence

1.报错的代码行：
`
with open("README.rst") as f:
    readme = f.read()
`
2.将代码改为：
`
with open("README.rst", encoding='utf-8') as f:
    readme = f.read()
`

**Comment by codeif** [comment]
多谢， 已改
